### ISSUE TITLE
translate docs into Chinese

### ISSUE THREAD

**Issue by Youjingyu** [clinicjs/node-clinic#113]
I want to translate [node clinic docs](https://clinicjs.org/documentation/) into Chinese. But the document page is a single page application. It's difficult to fork. Is there an esay way to translate it and keep the same reading experience with the official doc. if not，I have to  translate it with markdown in a diffrent repository.

**Comment by conoro** [comment]
@Youjingyu We'd love to have the docs in multiple languages! We're now investigating the best way of enabling this and will let you know.

**Comment by Youjingyu** [comment]
@conoro  i have translated part of the docs at [clinic-doc-ch](https://youjingyu.github.io/clinic-doc-ch/getting_started.html). if it's possible to merge into official docs, i will do.

**Comment by DylanC** [comment]
@conoro - Do you know where is the source of the docs?

**Comment by RafaelGSS** [comment]
The website is now public! Feel free to send PR if you want https://github.com/clinicjs/clinicjs-site
