### ISSUE TITLE
0x does not support clustering.

### ISSUE THREAD

**Issue by ledbit** [clinicjs/node-clinic#179]
Trying out clinic on our application which uses clustering to scale up results in the following error messages 

```
{"time":"2019-07-22T04:53:32.398Z","channel":"cribl","level":"error","message":"uncaughtException","error":{"message":"0x does not support clustering.","stack":"Error: 0x does not support clustering.\n    at EventEmitter.cluster.on (/usr/local/lib/node_modules/clinic/node_modules/0x/lib/preload/no-cluster.js:4:9)\n    at EventEmitter.emit (events.js:198:13)\n    at EventEmitter.emit (domain.js:448:20)\n    at emitForkNT (internal/cluster/master.js:222:11)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}}

net.js:268
    err = this._handle.open(fd);
                       ^

Error: EEXIST: file already exists, uv_pipe_open
    at new Socket (net.js:268:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/0x/lib/preload/redir-stdout.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:899:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
```

## Environment

* Clinic.js version: 4.1

* Node.js version: 10.16.0

* Browser name and version:

* Operating system and version: Linux ledion-vm 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davidmarkclements** [comment]
Clustering support is non-trivial - on top of the technical challenge, it would also require UI adaptation. On top of that if they're all the same instance, then the output will essentially be duplicative. The effort involved in providing this far exceeds the result. 

The solution is to profile without clustering (you could use an ENV flag or something to conditionally not cluster)

**Comment by ledbit** [comment]
>The solution is to profile without clustering (you could use an ENV flag or something to conditionally not cluster)
That's precisely what I ended up doing. Would be nice to call this out in the docs.

**Comment by makarov-roman** [comment]
Is there are way to run profiling programmatically?
I'm using SocketCluster which is not able to run as a single instance, it has at least one main thread and one worker.

**Comment by DylanC** [comment]
Dup of #96
