### ISSUE TITLE
SIGSEGV received when using worker_thread

### ISSUE THREAD

**Issue by MikeYermolayev** [clinicjs/node-clinic#185]
Hi, I have an app with support of worker_threads and as I can see node clinic can't work with that( 
As soon as I start it I receive
 
```
/usr/local/lib/node_modules/clinic/bin.js:536
      if (err) throw err
               ^

Error: process exited by signal SIGSEGV
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/@nearform/doctor/index.js:114:13)
    at Object.onceWrapper (events.js:297:20)
    at ChildProcess.emit (events.js:209:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

Is there any way to get around this? Putting env variables here and there is a little bit problematic in our codebase so would be nice to have some other options to do that

Thanks in advance!

## Environment
* Clinic.js version: v4.1.0 
* Doctor version: v4.0.6

* Node.js version: v12.9.0

* Operating system and version: OS X 10.14.4

**Comment by gajus** [comment]
This is a bummer. @goto-bus-stop is there a workaround for this?

**Comment by DylanC** [comment]
@MikeYermolayev @gajus - worker_threads are not supported currently. I don't think we have a work around for this.

**Comment by DylanC** [comment]
Dup of #96
