### ISSUE TITLE
Node clinic, bubleproof dont finish close process

### ISSUE THREAD

**Issue by aldarund** [clinicjs/node-clinic#189]
## Expected Behavior
Process closed and report generated on ctrl+c\

## Current Behavior
app is stuck on closing. 
/ Received Ctrl+C, closing process...
and thats it - it just there for hours
Happens on both bubbleproof and doctor
![image](https://user-images.githubusercontent.com/571159/65815177-b109f380-e1f4-11e9-9ca6-f5e488aac2df.png)

## Steps to Reproduce (for bugs)
https://www.dropbox.com/s/vt3kyj7jgef8qr8/vxcv.zip?dl=0
yarn install, yarn build, yarn nc

## Environment

* Clinic.js version: v4.1.0

* Node.js version: 12.10

* Browser name and version:

* Operating system and version:
win 10

**Comment by DylanC** [comment]
@aldarund - First you need to build your code and then pass the result into Clinic. Eg. npm run build.

Then pass your dist folder to Clinic.

**Comment by aldarund** [comment]
@DylanC thats not how it work. nuxt dont launch from dist. It launch from node modules js file that process dist. And i do build. And other tools e.g. doct work fine this way

**Comment by vaskinyy** [comment]
I just got the same issue. 

It works fine when I run `clinic doctor -- node index.js`, but it closes a process indefinitely after `clinic bubbleprof -- node index.js`

**Comment by JustDoItSascha** [comment]
Same problem here on bubbleprof. Doctor and Flame works fine.

**Comment by tanvirrb** [comment]
Same issue. clinic doctor is working fine. But clinic bubbleprof is getting hanged.

**Comment by RafaelGSS** [comment]
@tanvirrb Could you open a new issue with a reproduction code along with your system specifications? This issue is old and likely the problem is slightly different.

**Comment by Eddie344** [comment]
@aldarund i get the same problem, did u find a way to solve this problem?

**Comment by Prince-Bhagat** [comment]
I found one sort of  hacky solution. If bubbleprof is not stoping process after Ctrl + C , We can add the code to  stop the process for Ctrl + C. Adding below code to the node app worked for me.

`// Overwrritng the SIGINT Event
process.on ('SIGINT',() => {
  console.log('You clicked Ctrl+C!');
  process.exit(1);
});
`

**Comment by tomasz-szymanek** [comment]
@Prince-Bhagat Problem still occurs, even with this fix:

^CYou clicked Ctrl+C!
[    ] Received Ctrl+C, closing process...You clicked Ctrl+C!
[  ==] Received Ctrl+C, closing process...process exited with exit code 1
[  ==] Analysing dataError: premature close
    at onclosenexttick (/opt/homebrew/lib/node_modules/clinic/node_modules/end-of-stream/index.js:53:86)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
FAIL

**Comment by tomasz-szymanek** [comment]
@aldarund the problem i still occuring, please reopen this

**Comment by ajshortt** [comment]
Also having this issue on an Astro app. Was there not a solution in the end?
