### ISSUE TITLE
Cannot read property 'once' of null

### ISSUE THREAD

**Issue by jerikchan** [clinicjs/node-clinic#223]
resource.owner.once('listening', function () {
                         ^

TypeError: Cannot read property 'once' of null
    at /home/faier/.npm-global/lib/node_modules/clinic/node_modules/on-net-listen/index.js:14:26
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

steps:
i. npm i -g clinic
clinic -v -> v5.0.0
clinic doctor -v -> v4.1.1

ii. git clone https://github.com/nearform/node-clinic-doctor-examples.git
cd node-clinic-doctor-examples && npm install

iii. clinic doctor --autocannon [ / ] -- node ./slow-io
![image](https://user-images.githubusercontent.com/16037149/76607120-6257d800-654e-11ea-9678-93589df0366a.png)

when i open the html file, it show some errors:
![image](https://user-images.githubusercontent.com/16037149/76607394-e0b47a00-654e-11ea-9340-d127c360d07d.png)

**Comment by DylanC** [comment]
@jerikchan - Can you provide your Clinic version and Doctor version? Also an example we can run to reproduce this issue would be great!

**Comment by jerikchan** [comment]
> @jerikchan - Can you provide your Clinic version and Doctor version? Also an example we can run to reproduce this issue would be great!

Thank you for your reply, I have added some examples

**Comment by RafaelGSS** [comment]
In the latest version of clinicjs it's working fine. Feel free to re-open in case of some mistake.
