### ISSUE TITLE
can I use this to check cpu and memory performance of jest tests?

### ISSUE THREAD

**Issue by sibelius** [clinicjs/node-clinic#228]
can I use this to check cpu and memory performance of jest tests?

**Comment by jasnell** [comment]
in theory, yes, but there are limitations. For the profile (and analysis) to be meaningful, the test will need to generate a load against the code you are testing and you'll want to make sure that the test infrastructure itself is not throwing off the results.

It's also worth noting that clinic launches the node process with certain additional command line arguments and instrumentation injected. How clinic launches the process may not be compatible with how many test runners launch the process

**Comment by daton89** [comment]
is there any example with jest to detect memory leaks?

**Comment by pbrain19** [comment]
Way over due!
