### ISSUE TITLE
how to use clinic doctor on typescript project

### ISSUE THREAD

**Issue by sringly** [clinicjs/node-clinic#253]

**Comment by llfylwg** [comment]
please has someone can tell me ?

**Comment by jasnell** [comment]
clinic doctor should run fine on any transpiled typescript project. To answer your question we'd need to know a bit more about how you have your application set up to run.

**Comment by HanPeiyang** [comment]
For example,my project is run by ` ts-node --files index.ts`,how can i use clinic for it?

**Comment by HanPeiyang** [comment]
> clinic doctor should run fine on any transpiled typescript project. To answer your question we'd need to know a bit more about how you have your application set up to run.

Please look my new comment,thanks!

**Comment by KirillCherkalov** [comment]
@llfylwg  hi. try running the transpiler version of your code. First, you need to make a build so that the `dist` folder appears.
Then you can run your code
`clinic doctor --on-port 'autocannon localhost:$PORT' --  node _paste_entry_point_here_`
In my case this is:
` clinic doctor --on-port 'autocannon localhost:$PORT' --  node dist/src/main.js`

**Comment by MichaelLeeHobbs** [comment]
I am adding this for anyone who stumbles upon this in the future. I added the following to out package.json scripts. Shows how to transpile and config dotenv with custom .env file while using clinic.js.

```json
"clinic:heap": "tsc -p tsconfig.json && clinic heap -- node -r dotenv/config dist/index.js dotenv_config_path=dev1.env"
```

Additionally, if you are handling signals in your app, you will need something like:

```typescript
// For development, we don't want to handle signals, so we can let clinic.js do its thing
if (process.env.NODE_ENV !== 'development') {
  process.on('SIGINT', handleSignal)
  process.on('SIGTERM', handleSignal)
}
```

Note: You may want to create a new NODE_ENV that is closer to production than `development` might be. In our case, `development` changes how our logging works but did not matter for the purposes of our clinic.js usage.
