### ISSUE TITLE
How could i see only part of my application?

### ISSUE THREAD

**Issue by ElfenLiedGH** [clinicjs/node-clinic#262]
## Expected Behavior
I want to have a possibility of view for only one part of my app.

I have method in my app

```

async makeFile(file){

       const dataStream = file
               .pipe(baseTransformation)
               .pipe(findLinks)
               .pipe(checkChunk)
               .pipe(getCalc)
               .pipe(prepareResult)
               .pipe(addConvertSums)
               .pipe(groupResult);
             dataStream.pipe(prepareCSVFile);
             dataStream
               .pipe(prepareDataForClientFiles)
               .pipe(generateClientFiles)
               .pipe(zipFiles);

       return new Promise((rs)=>{
          zipFiles.on('finish', rs)
       })

}
```

Threre're part of my stream. And i don't know which part is the slowest and could'n see full flame for only my stream
![image](https://user-images.githubusercontent.com/9973357/93340262-456dcb80-f835-11ea-8ced-2e971fa65325.png)

## Current Behavior
I have quite big app that has a lot of background and startup processes. I want to take analysis of one stream. The stream works about 10 minutes but it lost in 1000 another calls and ticks. No one stream part has the common core (but if we look into stack trace of node 12+ we could see it)

## Sample upload

https://upload.clinicjs.org/private/2c9fb22a6ecec3c4025906eb8f4002433ebd66095e8eb69f85550904c2e954f4/23.clinic-flame.html

## Environment

* Clinic.js version: 7.0.0

* Node.js version: 12.18.3.

* Browser name and version: Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

* Operating system and version: Windows 10

**Comment by mcollina** [comment]
Unfortunately it is not currently possible to isolate a specific functions and related stacks. Technically, I fear this is not feasible at all.

**Comment by ElfenLiedGH** [comment]
@mcollina 

![image](https://user-images.githubusercontent.com/9973357/93437499-bc0dd600-f8d4-11ea-9ae2-2260f1e11ddd.png)
 V8 has information about full stack.

**Comment by ElfenLiedGH** [comment]
@mcollina 
![image](https://user-images.githubusercontent.com/9973357/93437734-fe371780-f8d4-11ea-8b84-bb28a0e193ae.png)
V8 has full information about it.

**Comment by mcollina** [comment]
Not really in the profiler or where we load the data from. Anyway, I'll be happy to review a PR.

**Comment by ElfenLiedGH** [comment]
@mcollina if you give me the path where you load the data I could try.

**Comment by mcollina** [comment]
https://github.com/davidmarkclements/0x here it is!

**Comment by ElfenLiedGH** [comment]
@mcollina thx
