### ISSUE TITLE
Log file is not generated after process exit

### ISSUE THREAD

**Issue by bradphelan** [clinicjs/node-clinic#277]
The error message should display the pattern for better diagnosis. For reference the pattern being looked for is

```
node_trace.*.log
```

``C:\Users\brad\AppData\Roaming\npm\node_modules\clinic\node_modules\@nearform\node-trace-log-join\index.js`` 

I can confirm that no file matching that pattern was created in the directory or below from which I ran

```
npx clinic doctor -- node build/server.js
```

_Originally posted by @bradphelan in https://github.com/clinicjs/node-clinic/issues/257#issuecomment-769650295_

**Comment by bradphelan** [comment]
I've found the source of the problem. The nodejs server was not gracefully shutting down. Adding a SIGINT handler, closing the server and calling process.exit seems to fix the issue.

```
  const s = server.listen(config.port, callback);

  process.on('SIGINT', async function onSigint() {
      console.info('Got SIGINT (aka ctrl-c). Graceful shutdown ', new Date().toISOString());
      await s.close()
      console.log('server closed');
      process.exit();
  });
```

Perhaps this could be added to the doc or in the error handling.

**Comment by mcollina** [comment]
Thanks for the good investigation! Would you like to send a PR to address this?

**Comment by bradphelan** [comment]
No sorry

**Comment by robross0606** [comment]
Would this problem be similar on Windows since it doesn't issue proper SIGINT to Node.js?

**Comment by RafaelGSS** [comment]
The latest version of Node.js v18 changed its behavior to handle signal events and it affected Clinic.js. We're tracking it on #393.

**Comment by robross0606** [comment]
I'm not on v18. I'm on v14 and must stay there for now.

**Comment by RafaelGSS** [comment]
It should be related to https://github.com/clinicjs/node-clinic-doctor/issues/363. I see you already commented there. Let's keep the discussion there.

**Comment by robross0606** [comment]
Okay, wasn't sure which one was causing it because I see no `node_trace.*.log` files at all.
