### ISSUE TITLE
How can i use clinic.js with serverless?

### ISSUE THREAD

**Issue by destbreso** [clinicjs/node-clinic#279]

**Comment by mcollina** [comment]
unfortunately no.

**Comment by willfarrell** [comment]
You could wrap the lambda in a simple http server. Here is what I'm doing for middy to test common use cases:

https://github.com/middyjs/middy/pull/649/files#diff-8c4d03273d00e3d33055f5fe1f623609a05fdb2063513bccf45eac55f3af4ada

Of course you would have to customize to meet your needs.

In theory you could run `serverless-offline` but expect that would add an excessive overhead into your tests.
