### ISSUE TITLE
clinicjs.org lists GPL3 License in the footer

### ISSUE THREAD

**Issue by RodEsp** [clinicjs/node-clinic#281]
## Expected Behavior

https://clinicjs.org/ should correctly show MIT License in the footer

## Current Behavior

https://clinicjs.org/ shows GPL3 License in the footer
![image](https://user-images.githubusercontent.com/1084688/114885419-a01fd380-9dd4-11eb-8397-9d3de994d165.png)

## Steps to Reproduce (for bugs)

1. Go to https://clinicjs.org/
2. Scroll to the bottom

**Comment by csdinos** [comment]
<img width="1428" alt="Screenshot 2022-01-03 at 19 24 22" src="https://user-images.githubusercontent.com/8160383/147965752-a23dbbbf-451d-4a83-9949-8e6ca690e2a7.png">
I think this can be closed now, right?
