### ISSUE TITLE
Doctor + Flame works, Bubbleprof dies

### ISSUE THREAD

**Issue by fabiancook** [clinicjs/node-clinic#282]
> I absolutely understand that this ticket may be an exception to the target audience, but it raises a couple of time bench marks for both doctor and flame vs base
> I can provide a generic repo that doesn't contain this exact code but produces the same result, but I fully expect this ticket to not require any further investigation past this. 

## Expected Behavior

Running `npx clinic bubbleprof -- node scripts/prerender.js` _should_ work. 

## Current Behavior

Running `npx clinic bubbleprof -- node scripts/prerender.js` causes a ` JavaScript heap out of memory` error. 

Output: https://gist.github.com/fabiancook/d4e0fec2701ea74c1e6e74be2dd24dd2 

The html output says 55ms of total time. 

## Steps to Reproduce

0. run `node scripts/prerender.js` 
1. run `npx clinic flame -- node scripts/prerender.js` (produces result correctly, see samples) 
2. run `npx clinic doctor -- node scripts/prerender.js` (produces result correctlty, see samples)
3. run `npx clinic bubbleprof -- node scripts/prerender.js` 

## Sample upload

https://happy-goldberg-6922cd.netlify.app/30174.clinic-flame.html
https://clever-franklin-66a4f2.netlify.app/32633.clinic-doctor.html

## Environment

* Clinic.js version: v8.0.1

* Node.js version: 15.14.0

* Operating system and version: macOS 10.15.7

## Some background

Pre-render contains 131,222 microtasks, and 7,687,595 promises
The promise count and microtasks do not change in between the different script runs. 

Timing:

|                  |       ms |
|-----------|-------|
|Node         | 14,212 |
|Flame        |19,564|
|Doctor       |97,634|

![image](https://user-images.githubusercontent.com/4337080/117536844-8d09c780-b051-11eb-9907-2cba30326871.png)

**Comment by jasnell** [comment]
The out of memory error would be expected here, unfortunately. Bubbleprof works by getting Node.js to generate a trace events file, which is a JSON document. It contains entries for every async resource created during the benchmark run. Bubbleprof then needs to parse that json document and generate an in-memory graph that is used to generate the visualization logic. With that many async resources, this ends up stressing the memory way too much and bubbleprof dies

**Comment by fabiancook** [comment]
Yeah no worries at all, I figured that was the case. 

I will close this as I believe it doesn't _require_ follow up from here. 

--------------

An idea though is moving where that data is collected, having that core thread dedicated to the task at hand. Whether or not that makes sense in the case of bubbleprof or not I am unsure. For small scale profiles I can see this being a non problem too which may be bubbleprofs target audience. 

----------------

Maybe I should just run smaller workloads too 😛
