### ISSUE TITLE
win 10 does not recognize clinic.js package

### ISSUE THREAD

**Issue by devPryze** [clinicjs/node-clinic#287]
## Expected Behavior

After installing with npm i -g clinic , it does not recognize the clinic command

## Current Behavior

clinic doctor --on-port 'autocannon -c 100 -d 5 localhost:3000' -- node 2.js 
clinic : The term 'clinic' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the   
name, or if a path was included, verify that the path is correct and    
try again.
At line:1 char:1
+ clinic doctor --on-port 'autocannon -c 100 -d 5 localhost:3000' --    
no ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (clinic:String) [], Comm  
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* Clinic.js version:

* Node.js version:

* Browser name and version:

* Operating system and version:

**Comment by RafaelGSS** [comment]
Please, check if your node/npm is installed properly
