### ISSUE TITLE
How to support cluster server.js

### ISSUE THREAD

**Issue by lifefloating** [clinicjs/node-clinic#288]
## Expected Behavior
how to support cluster mode:, eg:  require('cluster').fork()

## Current Behavior
not support

## Sample upload
Error: clinic doctor does not support clustering.

## Environment
latest

* Node.js version:
Node.js v12.13.1

* Browser name and version:

* Operating system and version:
* centos 7.9

**Comment by lifefloating** [comment]
111111
how to solve

**Comment by RafaelGSS** [comment]
> Error: clinic doctor does not support clustering.

As mentioned in the cli output, we currently don't support clustering.
