### ISSUE TITLE
how to use clinicjs with autocannon --har FILE option

### ISSUE THREAD

**Issue by hemendpatel** [clinicjs/node-clinic#289]
Autocannon is use requests from the HAR file to generate data. 
ie autocannon --har ./localhost.har -d 3 https://localhost:4213
  
But how to use it with clinicjs. I'm running my server and then clinic doctor command as --har require url.
Step 1 : node server.js
Step 2 : clinic doctor --autocannon --har ./localhost.har -d 3 http://localhost:4213

The second command is not working, do we have any option to use clinic js against url?

**Comment by RafaelGSS** [comment]
It's not possible because the clinicjs must wrap your application, so in your case, you need to:

`clinic doctor --autocannon [ --har ./localhost.har -d 3 ] -- node server.js`
