### ISSUE TITLE
Flamegraphs is not working properly in v16+

### ISSUE THREAD

**Issue by RafaelGSS** [clinicjs/node-clinic#293]
## Current Behavior

@mcollina has an insight about the flame graphs is not working properly in the latest versions of Node.js.
I'll be looking at it and update in this issue.

**Comment by RafaelGSS** [comment]
Well, I was debugging the:

> The stream never emit close event properly. This is never called (at v16) for some unknown reason.

And I've discovered that on `v15.8.0` it's working, but in `v15.9.0` it starts to fail. Well, after `git bisect` looks like https://github.com/nodejs/node/pull/37300 has added this behavior. 

I also did:

`git revert 521c08dee15ce8ada35571c94a4b6883ae00d41b` over `v15.9.0` and it's working fine. However, since it only affects the _auto close_ application, we've decided to no go through it and keep the focus on the flamegraph differences between those versions.

**Comment by simoneb** [comment]
Interesting finding @RafaelGSS, though somewhat surprising as that change (at least in my eyes) doesn't seem to carry any functional differences that would explain the change in behavior we're seeing. Do you have any clue as to why this is happening? How likely do you think it may be that the actual reason is something related to that commit, but not specifically that commit?

**Comment by RafaelGSS** [comment]
@simoneb I'm not sure, but looks like was specifically this commit since if I revert only that one, it works. So, I would say that the write stream was affected, I mean, it's hard to affirm it without an easily reproducible code.

**Comment by RafaelGSS** [comment]
I did a comparison between `flame` on `v14.15` and `v16.6` and they look pretty similar, the biggest difference looks like in the context filters. 

Look at the following screenshot:

![image](https://user-images.githubusercontent.com/26234614/139719125-fad0bd13-3699-4205-bdf6-173b6b1135df.png)


Node v14 and v16 at respectively left and right sides. If you check the filter context we have the following:

- v14 consider `internal/*` as `node` context

![image](https://user-images.githubusercontent.com/26234614/139721045-3759f331-0f6a-4672-a691-e5c1b83aae29.png)

- v16 consider `internal/*` as V8 context

![image](https://user-images.githubusercontent.com/26234614/139721154-29501b66-886b-441a-b7e9-59bddf60878a.png)

---

So, I feel that there are no issues so far, only filters adjustment. By the way, I'm assuming that `internal/*` should be placed as `node` context instead of `v8`, right?

### Additional considerations

I've also created the profiling through `linux_perf` just to make sure if there are missed translations through node versions, but they look pretty similar.

**Comment by mcollina** [comment]
> So, I feel that there are no issues so far, only filters adjustment. By the way, I'm assuming that internal/* should be placed as node context instead of v8, right?

Yes exactly!
