### ISSUE TITLE
How to see elapsed time for flame graph items?

### ISSUE THREAD

**Issue by jeremy-w** [clinicjs/node-clinic#294]
## Expected Behavior
I can readily see, not just the fraction of overall profiling time spent in a portion of the graph, but the elapsed time: a hot stack that runs for a small fraction of a second might not be worth going after. (I see that bubble does display info like this, so I'm hoping I'm just missing something obvious. 🤞 )

## Current Behavior
I can't work out where to see elapsed time anywhere in the UI.

## Steps to Reproduce (for bugs)

1. run a clinic flame
2. look at the UI when it opens up

## Screenshot
1.7% of what? how many seconds is that?

![Screen Shot 2021-10-27 at 12 00 35](https://user-images.githubusercontent.com/29010/139103229-e3ce5ebe-f0e3-415a-8df2-2fe07bdbe79f.png)

## Environment

* Clinic.js version:

```
> clinic flame -v
v9.0.0 (0x v4.11.0)
```

* Node.js version:

```
> node -v && npm -v
v14.17.3
6.14.13
```

* Browser name and version: Firefox 94.0b7 (64-bit)

* Operating system and version: 

```
> sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

**Comment by klausXR** [comment]
I'm also interested in this

**Comment by waseemshahwan** [comment]
+1

**Comment by RafaelGSS** [comment]
Clinic.js now shows the time-elapsed on the header. This should make the percentage calculation better. Please note that the intention of flamegraphs is to abstract the time. If you want to know samples over time you need to check flamecharts.
