### ISSUE TITLE
Clinic overhaul

### ISSUE THREAD

**Issue by simoneb** [clinicjs/node-clinic#298]
This is an umbrella issue for a clinic overhaul which will require the following high level activities to be done.

### Rebrand

This is in order to encourage more contributions by moving the packages out of the NearForm organization.

- [x] Create a new npm organization called `clinic`
- [x]  Rename all packages to remove the @nearform scope and replace with @clinic scope. All except the `clinic` package which lives in this repository, which is already without prefix and should stay without prefix
- [x] Release new versions of all the packages
- [x]  Make sure all new packages in the new org require 2FA to be published
- [x] Invite myself, @mcollina and @jasnell to the new org
- [x]  Deprecate all the older versions of the packages

### Documentation

- [x] heap profiler is missing from the website as it's a new entry, we should write docs for it similarly to what we have for the other tools in the clinic suite. https://clinicjs.org/

**Comment by jasnell** [comment]
Very happy to see the activity here. I was getting a bit worried

**Comment by RafaelGSS** [comment]
Could somebody give me access to: https://github.com/clinicjs/node-trace-log-join?

**Comment by simoneb** [comment]
@RafaelGSS done

**Comment by RafaelGSS** [comment]
Just for the record, packages that were deprecated:

- https://www.npmjs.com/package/@nearform/bubbleprof
- https://www.npmjs.com/package/@nearform/doctor
- https://www.npmjs.com/package/@nearform/flame
- https://www.npmjs.com/package/@nearform/trace-events-parser
- https://www.npmjs.com/package/@nearform/clinic-common
- https://www.npmjs.com/package/@nearform/node-trace-log-join
- https://www.npmjs.com/package/@nearform/clinic-heap-profiler
