### ISSUE TITLE
TODO: Updates to clinic doctor recommendations

### ISSUE THREAD

**Issue by jasnell** [clinicjs/node-clinic#315]
@mcollina @clinicjs/members  ... just leaving this as a todo. We need updates to clinic doctor recommendations such that the heap profiler tool is recommended when doctor detects memory issues.

**Comment by RafaelGSS** [comment]
I'm not sure if it's was implemented, so I have transferred to the main repository to get more traction on it

**Comment by mcollina** [comment]
This was never implemented.
