### ISSUE TITLE
Is it possible to attach to an existing node process?

### ISSUE THREAD

**Issue by kmamal** [clinicjs/node-clinic#322]
Or does the target process always have to be launched via the `--` args to clinic itself?

**Comment by RafaelGSS** [comment]
It should be always launched via `--` args. Node Clinic needs to wrap your application to track data.

**Comment by ronag** [comment]
What's your recommendation in regards to profiling things running in production?

**Comment by RafaelGSS** [comment]
Usually `linux_perf` does it very well. There are some libraries which might help you as well:

- https://github.com/mmarchini/node-linux-perf

ref:

- https://github.com/nodejs/diagnostics/issues/148
- https://blog.rafaelgss.com.br/node-cpu-profiler

**Comment by rluvaton** [comment]
What about profiling IO bottlenecks?
