### ISSUE TITLE
bug: Analysing dataError: ENOENT: no such file or directory [...]<pid>.clinic-doctor-processstat

### ISSUE THREAD

**Issue by tony-go** [clinicjs/node-clinic#333]
Hi 👋 

Here I bug I faced today. I'm obviously available to help 🤚. Didn't have time to debug yet. If you have any insights feel free to share it ^^

## Expected Behavior
A `*.clinic-doctor-processstat` file should be generated.

## Current Behavior
The doctor command doesn't work due to this file missing.

## Steps to Reproduce (for bugs)

1. Use this `fail.js`script:
```js
#!/usr/bin/env node

const async = require('async');
const shell = require('shelljs');

module.exports = function (exit) {
  async.waterfall([
  function (next) {
    next();
  },
  function (next) {
    next();
  }
  ], exit);
};

!module.parent && module.exports(shell.exit);
```

1. Run `clinic doctor -- node fail.js`
2. Got this error:
```bash
Analysing dataError: ENOENT: no such file or directory, open '.clinic/7063.clinic-doctor/7063.clinic-doctor-processstat'
```

## Sample upload
<img width="328" alt="Screenshot 2022-02-07 at 17 06 58" src="https://user-images.githubusercontent.com/22824417/152827108-272a2e01-35aa-4c89-b760-8e8ce0e21101.png">

## Environment
* Clinic.js version: `v11.0.0`
* Doctor version= `v9.2.1`
* Node.js version: `v17.4.0`
* Npm: `v8.3.1`
* Browser name and version: Firefox 96.0.3
* Operating system and version: OSX 12.1.0

**Comment by tony-go** [comment]
Yeah, @RafaelGSS ^^  Updated!

**Comment by vamshi9666** [comment]
@tony-go  did you get it fixed ?

**Comment by tony-go** [comment]
> @tony-go did you get it fixed ?

Nope, sorry :/

**Comment by Ceres6** [comment]
Hi! I'm working to debug the problem. If anyone has found anything yet please let me know.

**Comment by Ceres6** [comment]
Hi again!

The problem seems to be that those functions are running and exiting before the setTimeout callback that schedules `processstat` writes is triggered. 

Making any of the functions go over a `setTimeout` or `nextTick` would resolve the issue. 

Anyway if we want to support this case of functions running synchronously IMHO the easiest way forward is to initialise the file empty as it is currently being done with the other files. I can make a PR in node-clinic-doctor for that if that would be the desired approach. WDYT @RafaelGSS @simoneb?

**Comment by simoneb** [comment]
Thanks @Ceres6 , I'm not really sure about the solution here, but I'd like to understand the problem better. Is there a generalization we can do of this issue? Meaning, if we profile a program which does nothing, is this the behavior we obtain?

**Comment by RafaelGSS** [comment]
Basically, the script is forcing the exit by `shell.exit` so, I don't see it as a bug but as an expected condition.

If you just remove the shell.exit it should work.

**Comment by Ceres6** [comment]
That's right either removing the forced exit or having the program do something or be an ESM solves the issue. I'll go with the docs + error message then. Thanks @RafaelGSS
