### ISSUE TITLE
When running clinic shorter than 30second, get error "No files matching the pattern..." instead of handled error message like "running time too short"

### ISSUE THREAD

**Issue by fatihaziz** [clinicjs/node-clinic#346]
## Expected Behavior
Should show "profiling time to short" when the clinic running bellow 30-1 minute.

## Current Behavior
throwing error
`Error: No files matching the pattern found
    at notFound (...\node_modules\@clinic\node-trace-log-join\index.js:65:15)
    at combine (...\node_modules\@clinic\node-trace-log-join\index.js:24:34)
    at ...\node_modules\@clinic\node-trace-log-join\index.js:20:5
    at FSReqCallback.oncomplete (fs.js:180:23)
`
and inside .clinic/{PID}.clinic-doctor there is only 2 files:
- ...processstat
- ...system-info
expecting 3, lack of:
- ...traceevent

## Steps to Reproduce (for bugs)
1. create simple server.js
2. run `npx clinic doctor -- node server.js`
3. press ctrl + c bellow 30 seconds
4. getting error

## Sample upload
https://snipboard.io/wHgIbd.jpg

## Environment
DEVELOPMENT
* Clinic.js version:
Clinic - v11.1.0

* Node.js version: v14.17.6

* Browser name and version: Chrome

* Operating system and version: Win 11 + Cygwin

**Comment by RafaelGSS** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Also, can you share the "simple server.js"?

**Comment by fatihaziz** [comment]
surely, wait I will create a test

**Comment by fatihaziz** [comment]
closing for now since cannot reproduce the error
