### ISSUE TITLE
Can't run Clinic

### ISSUE THREAD

**Issue by paddotk** [clinicjs/node-clinic#348]
Hi,
I'm trying to get Clinic to work, but whatever I do, it can't seem to run it properly. I've spent hours trying what the docs say, searched for an answer, but found nothing that works.
The problem is likely not a bug but me running the wrong command; however the docs don't provide clear instructions for any project that doesn't work with the given command.
We have a Vuejs with Typescript project, setup with the Vue CLI. This uses Webpack under the hood, and it must run on port 8081.

It's unclear what I'm doing wrong, and would really like a better explanation in the docs on how this works.

## Attempts
- The docs simply state you have to run `clinic doctor -- node server.js` so I tried this, but with `src/main.ts` as the target since our project doesn't have a `server.js`. It gives me the error `Cannot use import statement outside a module`, referring to an import statement inside that file.
- Various people commented that adding `"type": "module"` to the package.json should resolve this, but if I do this and run Clinic, I get `Unknown file extension ".ts"`. It does generate a diagnostics html, but everything is empty.
- I added the packages `ts-node` and `nodemon` and tried with nodemon instead of node (`clinic doctor -- nodemon src/main.ts`)
- `clinic doctor -- npm run serve`
- I tried running the app first in a separate terminal, then attempted with `clinic doctor --on-port 8081 -- node src/main.ts`, `clinic doctor --on-port=8081 -- node src/main.ts`, and `clinic doctor --autocannon [ -m POST 'http://localhost:8081' ] -- node main.ts`
- After reading a comment here stating that you can build the app, then run Clinic, I ran a build then did `clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node dist/js/app.78a0b88f.js` where `dist/js/app.78a0b88f.js` is the generated file

## Environment
* Clinic version: 11.1.0
* Clinic doctor version: 9.2.1
* Node.js version: 16.14.1
* Browser name and version: not relevant
* Operating system and version: Windows 10
* Typescript version: 4.1.5

**Comment by RafaelGSS** [comment]
The clinic.js doesn't support typescript out-of-box, you should build your application first.

**Comment by lceihen** [comment]
> The clinic.js doesn't support typescript out-of-box, you should build your application first.
> 
> > After reading a comment here stating that you can build the app, then run Clinic, I ran a build then did clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node dist/js/app.78a0b88f.js where dist/js/app.78a0b88f.js is the generated file
> 
> And it works?

i make a simple http-server listen on 3000 and make sure clinic@11.1.0  has install on win10,use clinic doctor -- node server.js ,
 but is don't work,show that 

` clinic doctor is the first step in profiling your application. It will show you what kind of problem you are having and recommend the path forward.`

The problem is likely to a guide,how can i do for next ,thank

const http = require('http')

http
  .createServer((req, res) => {
    res.end('1')
  })
  .listen(3000, () => {
    console.log('success')
  })

**Comment by lceihen** [comment]
> The clinic.js doesn't support typescript out-of-box, you should build your application first.
> 
> > After reading a comment here stating that you can build the app, then run Clinic, I ran a build then did clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node dist/js/app.78a0b88f.js where dist/js/app.78a0b88f.js is the generated file
> 
> And it works?

i make a simple http-server listen on 3000 and make sure clinic@11.1.0  has install on win10,use clinic doctor -- node server.js ,
 but is don't work,show that 

` clinic doctor is the first step in profiling your application. It will show you what kind of problem you are having and recommend the path forward.`

The problem is likely to a guide,how can i do for next ,thank

const http = require('http')

http
  .createServer((req, res) => {
    res.end('1')
  })
  .listen(3000, () => {
    console.log('success')
  })

**Comment by MingLiCheng** [comment]
I am printing a log in [clinic/bin.js] outputting the parameters received on the command line
```javascript
  .register('doctor', catchify(async function (argv) {
    const version = require('@clinic/doctor/package.json').version
    const args = subarg(argv, {
      alias: {...})

   // add
    console.log('args', args)
```

I get the log

```shell
// run
clinic doctor -- node .\index.js

// result
args {
  _: [ 'node', '.\\index.js' ],
  help: false,
  h: false,
  version: false,
  v: false,
  'collect-only': false,
  open: true,
  debug: false,
  'sample-interval': '10',
  dest: '.clinic',
  '--': []
}
```

Then I try to use the new command

```shell
clinic doctor '--' node .\index.js
```

```javscript
args {
  _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  'collect-only': false,
  open: true,
  debug: false,
  'sample-interval': '10',
  dest: '.clinic',
  '--': [ 'node', '.\\index.js' ]
}
```
**clinic run**
I don't know why and haven't continued research

**Comment by RafaelGSS** [comment]
Could you create a reproducible code? Reference: https://stackoverflow.com/help/minimal-reproducible-example.
Feel free to open a new issue relating to the issue you are facing.
