### ISSUE TITLE
feature: support fastify-cli or npm script

### ISSUE THREAD

**Issue by Eomm** [clinicjs/node-clinic#352]
## Expected Behavior
I have a `fastify-cli` application that starts with this setup:

```
npm start

// where package.json start looks like:
// "start": "fastify start --require './configs/tracing.js' -l info --options app.js",
```

## Current Behavior
Error:

```
Clinic.js must be called with a `node` command line: `clinic doctor -- node script.js`
```

## Environment

> clinic "-v"
v11.1.0

> clinic "docktor" "-v" 
v9.2.1

* Node.js version: 16.14

**Comment by RafaelGSS** [comment]
try to change your `start`to:

`clinic doctor -- node ./node_modules/.bin/fastify start --require './configs/tracing.js' -l info --options app.js`

**Comment by Eomm** [comment]
Good suggestion!
It works
