### ISSUE TITLE
Heapprofiler doesn't finish

### ISSUE THREAD

**Issue by aferrando-tid** [clinicjs/node-clinic#353]
Hello.

Thank you so much for clinic, it's quite the awesome tool.

I have a problem with some service I work on, which might have a memory leak we're trying to diagnose.

For this, we're trying to use clinic heapprofiler.

The problem, though, is that this seems not to finish, and don't know if it's a problem of expected time or maybe a bug in the tool.

I'm launching said service in my machine with clinic doctor, launch our suite of performance tests, and then send SIGINT to the doctor process and it stops the service, shows data etc etc. This works fine.

On the other hand, doing the same with heapprofiler, it receives the SIGINT, doesn't seem to propagate it to the service even after 3 hours. It's not even saying analyzing, just "Received CTRL+C, closing process...".

The process doesn't seem to have received either the propagated signal as it would have stopped, as it does with the doctor case.

Any idea if we might be doing something wrong, or if it might be due to a data volume issue?

Thank you in advance

## Expected Behavior
heapprofiler ends and shows a report

## Current Behavior
heapprofiler doesn't end, nor seems to propagate the signal to the analysed process

## Steps to Reproduce (for bugs)
I'm not able to produce a repro which I would be able to share

## Sample upload
heapprofiler is not generating a sample

## Environment

* Clinic.js version: v11.1.0

* Node.js version: 
Node v16.15.0
npm 8.5.5

* Browser name and version:
not relevant as report is not generated

* Operating system and version:
* Ubuntu 22.04

**Comment by mcollina** [comment]
How long are you running heapprofiler and how much time are you waiting afterwards? Is the process doing something (is the CPU utilization high?)

**Comment by aferrando-tid** [comment]
The test take around 2 to 3 minutes

I'm waiting about 8 seconds from when the tests finish running before sending the signal

No, the process is not doing anything, or in any case I don't see any process launched after starting the service using a high % of CPU

**Comment by aferrando-tid** [comment]
The problem seems to be related to killing the clinic process from another terminal, but this doesn't happen when killing it using CTRL-C on the terminal I ran it on.

Should I close the issue?

**Comment by mcollina** [comment]
I think so, thanks!
