### ISSUE TITLE
Tests profiling support

### ISSUE THREAD

**Issue by 0xorial** [clinicjs/node-clinic#360]
I have a test suite (using mocha) which I want to profile. Is this use case supported?
If I run `clinic flame -- node ./node_modules/mocha/bin/mocha.js`, only thing I get in the output is the instruction of how to call clinic flame and nothing seems to happen.
(Running on Windows)

**Comment by 0xorial** [comment]
https://github.com/0xorial/mocha-clinic-test

**Comment by RafaelGSS** [comment]
Thanks, @0xorial I'll look at it soon as I have time

**Comment by RafaelGSS** [comment]
I gave it a shot today and it seems working fine

```console
rafaelgss@rafaelgss-desktop:~/repos/os/tests/mocha-clinic-test$ clinic flame -- node ./node_modules/.bin/mocha test/index.test.js
To generate the report press: Ctrl + C


  Array
    #indexOf()
      ✔ should return -1 when the value is not present (3291ms)


  1 passing (3s)

Analysing data
Generated HTML file is file:///home/rafaelgss/repos/os/tests/mocha-clinic-test/.clinic/25973.clinic-flame.html
```

Could you re-install and run it again? If that doesn't work, it might be related to your environment (windows).
