### ISSUE TITLE
Can't run Clinic on macOS

### ISSUE THREAD

**Issue by rubencosta13** [clinicjs/node-clinic#361]
## Expected Behavior
``clinic --help`` should print clinicjs informations, however on macOS (Version 13), upon installing doesn't behave as expected

## Current Behavior
When using ZSH and ``npm install -g clinic`` to install it, it works, however when running with the CLI command ``clinic`` ZSH returns ``zsh: command not found: clinic``

## Steps to Reproduce (for bugs)
1.Install globally clinic
2.Run ``clinic --help``

## Environment
* Clinic.js version: Can't obtain

* Node.js version: v16.16.0
* Npm version: 8.13.2

* Browser name and version: Chrome 103 on macOS (13)

* Operating system and version: OSX 13

**Comment by RafaelGSS** [comment]
cc @mcollina can you confirm that? I don't use macOS

**Comment by mcollina** [comment]
works perfectly here on Node v16.

**Comment by RafaelGSS** [comment]
> > works perfectly here on Node v16.
> 
> Thats odd, couldn't make it to work following the guide. (Installed node via homebrew)

Looks like it's not really installing it globally. `npx clinic --help` should works

**Comment by RafaelGSS** [comment]
try install the package again, please

**Comment by rubencosta13** [comment]
Working now!
