### ISSUE TITLE
encounter "Decoded message is not valid" when visualizing profile files

### ISSUE THREAD

**Issue by zongzheng123** [clinicjs/node-clinic#372]
Hello, thanks for read.
I got an error when I visualized my docker profile files and the detailed error is under the below

#,# Current Behavior

<img width="889" alt="image" src="https://user-images.githubusercontent.com/22883411/194696169-a03fcf36-48ce-40c9-9490-001c3b26f879.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* Clinic.js version: 12.0.0

* Node.js version: 16.14

* Browser name and version:

* Operating system and version:macOs 12.5.1

**Comment by RafaelGSS** [comment]
No reproducible code.
