### ISSUE TITLE
Inactive Clinic

### ISSUE THREAD

**Issue by gaurav-aggarwal0301** [clinicjs/node-clinic#373]
Team,

I didn't find any option to start a discussion on a query under clinic.js hence marking it in issue section.
Does clinic.js has any option that process can be linked to clinic at runtime without starting it or if process running with clinic so it will be in inactive mode till that time it is not marked active to collect desired data. This question comes where we don't want to start the process pre and post and keep the clinic in inactive mode for time outside in monitoring window.

**Comment by RafaelGSS** [comment]
Clinic.js can't be linked at runtime. It's designed for development mode.
