### ISSUE TITLE
`Error: process exited by signal SIGABRT` when doing `ctrl+c`.

### ISSUE THREAD

**Issue by r4wand** [clinicjs/node-clinic#396]
## Expected Behavior
I am expecting clinic.js to stop listing and start generating the HTML report files. 
## Current Behavior
When I do `ctrl+c` I get the following error.
`Error: process exited by signal SIGABRT
    at ChildProcess.<anonymous> (/home/rawand/.nvm/versions/node/v18.13.0/lib/node_modules/clinic/node_modules/@clinic/doctor/index.js:133:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)`

## Steps to Reproduce (for bugs)
 clone the sample clinic's repository.
 `git clone git@github.com:nearform/node-clinic-doctor-examples.git  `
`cd node-clinic-doctor-examples`
`npm i`

then start clinic 
`clinic doctor --on-port 'autocannon localhost:$PORT' -- node slow-event-loop`

## Environment
* Clinic.js version: v12.0.0 
* Docter version: v10.0.0

* Node.js version: v18.13.0

* Operating system and version:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by jonthomp** [comment]
We are also experiencing this; I think it's probably a duplicate of https://github.com/clinicjs/node-clinic/issues/393

**Comment by r4wand** [comment]
@jonthomp Thank you, updating to Node.js v19.7.0 fixed it. 
I'll close this issue as it's pretty much the same issue as the one you mentioned.

**Comment by Jason5Lee** [comment]
I have to use Node.js v18 for some specific reasons. Is there any workaround available?

**Comment by IslamWahid** [comment]
please add that to the docs
