### ISSUE TITLE
Flame: incorrectly detects `category` and `type` for projects with type: module

### ISSUE THREAD

**Issue by MrWaip** [clinicjs/node-clinic#446]
Hello. I was looking for bottlenecks in my svelte.kit project. The project uses esm modules by default.
And I was confused that all my source code was marked as Node JS.

## Expected Behavior
With esm module code have to be marked as `{ type: appName, category: 'app'}`

## Current Behavior
Now when I use esm modules my code marked as `core`.

```
# /analysis/frame-node.js
# at function getCoreOrV8Type

 getCoreOrV8Type (name, systemInfo) {
    // TODO: see if any subdivisions of core are useful
    const core = { type: 'core', category: 'core' }

    let type

    if (/\[CODE:RegExp]$/.test(name)) {
      type = 'regexp'
    } else if (!/(\.m?js)|(node:\w)/.test(name)) {
      if (/\[CODE:.*?]$/.test(name) || /v8::internal::.*\[CPP]$/.test(name)) {
        type = 'v8'
      } else /* istanbul ignore next */ if (/\.$/.test(name)) {
        return core
      } else if (/\[CPP]$/.test(name) || /\[SHARED_LIB]$/.test(name)) {
        type = 'cpp'
      } else if (/\[eval]/.test(name)) {
        // unless we create an eval checkbox
        // "native" is the next best label since
        // you cannot tell where the eval comes
        // from (app, deps, core)
        type = 'native'
      } else {
        type = 'v8'
      }
    } else if (/ native /.test(name)) {
      type = 'native'
    } else if (this.isNodeCore(systemInfo)) { # <------------------------------ here is bug
      return core 
    }

    return type
      ? { type, category: 'all-v8' }
      : null
  }

```

## Steps to Reproduce (for bugs)
Just try `node-clinic-flame-demo` with `"type":"module"` and import some function.

## Sample upload
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/37497663/227610054-bf158ee6-d279-45c1-8398-46a8948e94b0.png">

## Environment
* Clinic.js version: v12.1.0
* Flame version: v12.1.0 (0x v5.5.0)

* Node.js version: v16.19.1

**Comment by MrWaip** [comment]
I can assume that we can detect source code by using `/file\:\/\//.test(name)`

**Comment by RafaelGSS** [comment]
Which operating system are you using?

**Comment by MrWaip** [comment]
> Which operating system are you using?

Mac OS: 12.6 (21G115) (Monterey)
