### ISSUE TITLE
heapprofiler: wrong PID in the resulting file name

### ISSUE THREAD

**Issue by alexandervain** [clinicjs/node-clinic#452]
## Expected Behavior
The resulting file (`.clinic/555.clinic-heapprofiler`) of the `clinic heapprofiler -- node foo.js` command would contain the PID (555) of the "foo.js" process.

## Current Behavior
The file name contain the PID of the parent clinic process itself.

_This behaviour is different from all other `clinic` modes (`flame`, `doctor`, `bubbleprof`) where the used PID is the one of the child process._

## Steps to Reproduce (for bugs)
1. run `clinic heapprofiler --collect-only -- node app.js`
2. inspect the PIDs of the clinic process and the child "app" process
3. stop the clinic heapprofiler (CTRL-C)
4. Check the name of the generated result file

## Environment
* Clinic.js version: v12.1.0
* Heapprofiler version: v4.1.1
* Node.js version: v16.14.2
* Operating system and version: Debian GNU/Linux 10 (buster)

**Comment by RafaelGSS** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
