### ISSUE TITLE
Clinic Doctor not generating .html report with node v16

### ISSUE THREAD

**Issue by AlexGoranov** [clinicjs/node-clinic#456]
## Expected Behavior

I would expect a report to be created and opened in my web browser after closing the application with Ctrl + C.

## Current Behavior

Once I close the app I am getting the message: `^C[    ] Received Ctrl+C, closing process...`. Then a `node_trace.1.log` file has been created. It happens only when I run it with `npx clinic doctor -- node index` but not when I do `clinic doctor -- node index`. I have confirmed that my local and global versions are the same.

### To run the server I used:

`npx clinic doctor -- node index`

### The server I am running is:

```
const express = require('express')
const app = express()

app.get('/', function (req, res) {
  res.send('Hello World')
})

app.listen(3000)
```

## Environment

* Clinic.js version: v13.0.0
* Doctor version v11.0.0

* Node.js version:  `v16.18.1`

* Browser name and version:

* Operating system and version: macOS 13.4.1 (22F82)

**Comment by AlexGoranov** [comment]
Yes, it does

**Comment by RafaelGSS** [comment]
I didn't investigate it, but I believe it's because `npx` should have custom `process.on('SIGINT')` handlers. 

Try manually adding `process.on('SIGINT`, () => process.exit())` in your code
