### ISSUE TITLE
Question: Is this project active?

### ISSUE THREAD

**Issue by drodil** [clinicjs/node-clinic#474]
Just a question: is this project still active and are there any new releases to be expected?

**Comment by RafaelGSS** [comment]
I'm one of the maintainers, but I have to say this project doesn't get much of my time, so unless the issue is affecting me directly, it's unlikely to be solved (unless someone else created a PR), so I'm happy to review.

**Comment by simoneb** [comment]
I'm speaking on behalf of Nearform, who created this project, and unfortunately we are not actively maintaning this anymore either. The project still works to a certain extent, but given its tight coupling to Node's internals, we do expect things to stop working or not working consistently as Node.js evolves, which may partially be the case already now.

**Comment by RafaelGSS** [comment]
> we do expect things to stop working or not working consistently as Node.js evolves, which may partially be the case already now.

That's correct. Clinic.js does work on Node.js 20 and 22, but not accurate, and in fact for `kernel-tracing` it's almost not working with accuracy.

**Comment by drodil** [comment]
Ok, thanks for all the answers! 

Do you have any tips what could be useful for Node profiling besides this project? I somehow feel there are no good tools for that and it's something that is missing from the ecosystem. Sure Node itself can produce profiling information but visualizing it and digging in the data is not intuative.

**Comment by simoneb** [comment]
There are several blog posts from past years on [our website](https://www.nearform.com/insights/) about Clinic, although they're more descriptive than technical, and you will find largely the same information on the Clinic website.
